import { Command } from 'commander';
import { existsSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import {
  CLI_NAME,
  PM2_DAEMON_NAME,
  PM2_DASHBOARD_NAME,
  getFrameworkRoot,
  getStateRoot,
} from '../utils/elevate.js';

export const ecosystemCommand = new Command('ecosystem')
  .option('--instance <id>', 'Instance ID', 'default')
  .option('--org <name>', 'Organization name (auto-detected if not specified)')
  .option('--output <path>', 'Output file', 'ecosystem.config.js')
  .description('Generate PM2 ecosystem.config.js from agent configs')
  .action(async (options: { instance: string; org?: string; output: string }) => {
    const ctxRoot = getStateRoot(options.instance);
    // Same project-root discovery as enable-agent.ts so `elevate ecosystem`
    // works from outside the source checkout.
    let projectRoot: string;
    if (process.env.ELEVATE_FRAMEWORK_ROOT || process.env.CTX_FRAMEWORK_ROOT || process.env.CTX_PROJECT_ROOT) {
      projectRoot = getFrameworkRoot();
    } else {
      const canonical = join(homedir(), 'elevateos');
      projectRoot = existsSync(join(canonical, 'orgs')) ? canonical : process.cwd();
    }

    // Find all agents
    const agents: Array<{ name: string; dir: string; org?: string }> = [];

    // Scan orgs/*/agents/*
    const orgsDir = join(projectRoot, 'orgs');
    if (existsSync(orgsDir)) {
      for (const org of readdirSync(orgsDir, { withFileTypes: true })) {
        if (!org.isDirectory()) continue;
        const agentsDir = join(orgsDir, org.name, 'agents');
        if (!existsSync(agentsDir)) continue;
        for (const agent of readdirSync(agentsDir, { withFileTypes: true })) {
          if (!agent.isDirectory()) continue;
          agents.push({ name: agent.name, dir: join(agentsDir, agent.name), org: org.name });
        }
      }
    }

    if (agents.length === 0) {
      console.log(`No agents found. Add agents first: ${CLI_NAME} add-agent <name>`);
      return;
    }

    // Determine org: use --org flag, or auto-detect from first agent found
    const detectedOrg = options.org || agents.find(a => a.org)?.org || '';
    if (!detectedOrg) {
      console.error('Could not determine org. Use --org <name>.');
      return;
    }

    // Use dist/ in project root for all scripts
    const distDir = join(projectRoot, 'dist');
    const daemonScript = join(distDir, 'daemon.js');
    const dashboardDir = join(projectRoot, 'dashboard');
    // BUG-019 + cycle-2 finding: require BOTH package.json AND node_modules/.bin/next.
    // Without the second check, running `elevate ecosystem` before
    // `npm install` in dashboard/ produces a crash-looped PM2 entry that the
    // user sees as "dashboard keeps restarting". Better to silently skip the
    // dashboard entry if its deps aren't installed yet — the user can re-run
    // `elevate ecosystem` after `npm install` to add it.
    const hasDashboard = existsSync(join(dashboardDir, 'package.json')) &&
      existsSync(join(dashboardDir, 'node_modules', '.bin', 'next'));

    // BUG-002 fix: emit ecosystem.config.js as raw JS that resolves
    // process.env.CTX_INSTANCE_ID at PM2-startup time, not at generation time.
    // The previous JSON.stringify approach baked the instance id into the
    // generated file, so instance switching required regenerating the file.
    // Now: `ELEVATE_INSTANCE_ID=other pm2 restart elevate-daemon` just works.
    //
    // BUG-016 fix: bumped max_restarts from 10 to 50. PM2's max_restarts
    // controls how many times PM2 itself restarts the daemon if it
    // crashes — independent of in-daemon agent crash counting. 10 was too
    // low: a transient infrastructure wobble could exhaust retries before
    // the daemon stabilized. 50 leaves real headroom.
    //
    // BUG-019 fix: emit a dashboard PM2 entry alongside the daemon
    // so the dashboard runs under PM2 supervision instead of as an orphan
    // `npm run dev &` background shell job started by /onboarding. Now it
    // gets restart-on-crash, log files in ~/.pm2/logs/, and reboot survival
    // via `pm2 startup`/`pm2 save`. The dashboard PM2 entry is only added
    // if dashboard/package.json exists (to keep the generator working in
    // minimal/test installs).
    const dashboardAppBlock = hasDashboard
      ? `,
    {
      name: ${JSON.stringify(PM2_DASHBOARD_NAME)},
      script: 'npm',
      args: 'run dev',
      cwd: ${JSON.stringify(dashboardDir)},
      env: {
        PORT: process.env.PORT || '3000',
      },
      // Dashboard reads its real config from dashboard/.env.local — populated
      // by /onboarding Phase 7. PM2 just supervises the npm process.
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    }`
      : '';

    const content = `// AUTO-GENERATED by \`${CLI_NAME} ecosystem\`. Do NOT edit by hand.
// Re-run \`${CLI_NAME} ecosystem\` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means \`ELEVATE_INSTANCE_ID=foo
// pm2 restart ${PM2_DAEMON_NAME}\` switches instances without regenerating.
module.exports = {
  apps: [
    {
      name: ${JSON.stringify(PM2_DAEMON_NAME)},
      script: ${JSON.stringify(daemonScript)},
      args: '--instance ' + (process.env.ELEVATE_INSTANCE_ID || process.env.CTX_INSTANCE_ID || ${JSON.stringify(options.instance)}),
      cwd: ${JSON.stringify(projectRoot)},
      env: {
        ELEVATE_INSTANCE_ID: process.env.ELEVATE_INSTANCE_ID || process.env.CTX_INSTANCE_ID || ${JSON.stringify(options.instance)},
        ELEVATE_ROOT: process.env.ELEVATE_ROOT || process.env.CTX_ROOT || ${JSON.stringify(ctxRoot)},
        ELEVATE_FRAMEWORK_ROOT: ${JSON.stringify(projectRoot)},
        ELEVATE_ORG: process.env.ELEVATE_ORG || process.env.CTX_ORG || ${JSON.stringify(detectedOrg)},
        CTX_INSTANCE_ID: process.env.ELEVATE_INSTANCE_ID || process.env.CTX_INSTANCE_ID || ${JSON.stringify(options.instance)},
        CTX_ROOT: process.env.ELEVATE_ROOT || process.env.CTX_ROOT || ${JSON.stringify(ctxRoot)},
        CTX_FRAMEWORK_ROOT: ${JSON.stringify(projectRoot)},
        CTX_PROJECT_ROOT: ${JSON.stringify(projectRoot)},
        CTX_ORG: process.env.ELEVATE_ORG || process.env.CTX_ORG || ${JSON.stringify(detectedOrg)},
      },
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    }${dashboardAppBlock},
  ],
};
`;

    writeFileSync(options.output, content, 'utf-8');
    console.log(`Generated ${options.output} with daemon (manages ${agents.length} agents)${hasDashboard ? ' + dashboard' : ''}`);
    console.log('\nStart with:');
    console.log(`  pm2 start ${options.output}`);
    console.log('  pm2 save');
  });
